language: python
python:
- '3.5'
cache:
  directories:
    - cache
env:
  global:
    secure: c676c0obZAykv+zmrOtukP/TxCSa9BHamFo5glVN5AIfoBRRZs5hpBRR6dWYjZAs2Gdnv8ICXeOrV2yMvkJvAhzilJMkx88RRDlxrTEU+JiUDFWnzSu6fsqZ+ffHGQ3A5DhgLBF0EY8FVkSm2rapknekjoixFJr7BlMszMhw8SeRt5iXoVu+6BkLzk55P3w4grCSU1orzT/DK2dK4iBvqPRfp4WU22qgUrq0vE+B8xF6bLIJAP6w7G3tbNGjQ53UL6wGLlPXxiDFzk/a4poV9AGw+h4NuSEUV4/jFj01PlUUDqQfPU885kQA/j2o1Hv9RvTULpncgPCRO9AHMd3apRCSRkfgixakq4scsLq4ZxSfYY44nYCIhKHp7bmCm/CWrMaQD/E5K2s5tjFVF/ozfOG7cJpcHdmFBxdycnjrxKTMSvtQN8wZucGe1WwFKUv6i06+fC1lsqx1ydArC5gcVBKPPpmXCflcDRdM2AU5743+awidjItNjCFz/64+51qet/KiovzzVwgwYm837oZyAP8MZ+yiR0gEtXsNYrGXo2biId3qK776wIzQ2PebWlKUxK5pjWvWKjDFrfaBCg7L4dYGsHaz4GwTEsZ9OPEct+LJrVSlLxCYpFxOkNTM1GRQl/ya6OEBWEKYQCj5jL7fQgI33Mb7xIkRAxSY+XWPOfE=
  matrix:
  - CHANNELS=3
  - CHANNELS=2
  - CHANNELS=1
before_install:
- pip install --src ./src -e git+https://github.com/m-labs/migen.git#egg=migen
- pip install --src ./src -e git+https://github.com/m-labs/asyncserial.git#egg=asyncserial
- pip install --src ./src -e git+https://github.com/m-labs/misoc.git#egg=misoc
- pip install -e .
- pip install colorama
- pip install nose
- "./.travis/get-xilinx.sh"
script:
- nosetests -v
- python3 -m pdq.gateware.make -x $(pwd)/opt/Xilinx -c $CHANNELS
notifications:
  email: false
  slack:
    secure: ZZGXMH5AqEuzfE+OE0tRWT5b37ddNCv2U0YCaPo1Dh5iZaywJt0SXIilXJXp5+QNU9+wrihgetsmfLpWucW1qX2a15GAK8oFq1wMYXBMQIDPdf/Px5dwbSNPgEPjTPr3HKfePt2ctHy8si2gb693crP9dbAPmQMeHIPjqTYXluK2qOqMaMCpps5vsxvuns4EIH7SsvCz5j+i4LImOk+22NRRunQQXKRYRPxTGkF1JBPeIC5xBAfB6KlyS9l/RC7ELyEPVMEpfHop94mPFFDvQJrQu8WR/rfoexU6UJrSpBDCqAcqie19KIrVh1oLWKbnqAPQVfXHtbD3cgL/uPRCDcSDse7ZhnfPV2LNysP1NndCn6OL4mfF20WWxNS8t2TNqj0E3dBMlk3VHhLy/SrD+HArP+vDd9JZOAcw7t4Cn6x37sbqS3b42DbOIL+xRrXuwlJg0HyHpE0R304bqr98mlmEv3nnGPwlq92+OHKSE8PedAdF5vc2SQ/F8pB4UT20Purik43x53FPRN4gKrobvuVtObgxG0iEOxyMov2jbrnUgJt82lPVRWqh3+3S9BnQQt/enrYZ7UUIsjZ2p+Mf4hJbvYSnfmZfEiCcUtujY0K5G72ep8NtPaT+AHFmXsukdkOUpreFWXBh2GXW9fJjxTLMYysF/8Lxndu6YV7uSFc=
